apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-service-1-deployment
  labels:
    app: micro1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: micro1
  template:
    metadata:
      labels:
        app: micro1
    spec:
      containers:
      - name: micro1
        image: wilkhu90/micro1:0.0.1
        ports:
        - containerPort: 8118
          name: server
        - containerPort: 8000
          name: management

apiVersion: v1
kind: Service
metadata:
  name: micro-service-1-service
spec:
  ports:
  - port: 8118
    targetPort: 8118
    name: http
  - port: 8000
    targetPort: 8000
    name: management
  selector:
    app: micro1
  type: NodePort